all: arra-ros-tools-rviz.tex
	pdflatex arra-ros-tools-rviz.tex --quiet -interaction=batchmode
	pdflatex arra-ros-tools-rviz.tex --quiet -interaction=batchmode
	
clean:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz
	
cleanall:
	rm -f *.log *.toc *.aux *.nav *.out *.snm *.bbl *.blg *.synctex.gz arra-ros-tools-rviz.pdf
